### PR TITLE
Bug fixed: Program explodes when it has more than 2 variables assigned.

### LINKED ISSUE #1: Program explodes when it has more than 2 variable assignments.
# Replication

```
a = 10;b = 20;print(a);print(b)
```

The code just explodes... 😆

### PR DESCRIPTION
**Pull request by Zen0x7**
(Closes #1)

### CODE REVIEW

File: main.cpp [hunk 1]
```diff
@@ -134,6 +134,7 @@ std::string getValue(const std::string& identifier)
             value = type.value;
             founded = true;
         }
+        index++;
```
Comment (Zen0x7) [inline main.cpp:137]: This code fix that bug.
